In [1]:
import numpy as np

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.zeros((3,4,2))

a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
print(len(a))
print(a.size)
print(a.shape)


3
24
(3, 4, 2)


In [7]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [8]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#numeros aleatorios entre 0 y 1 range[0, 1]
a = np.random.random((10,4))

a

array([[0.03038324, 0.83930041, 0.36571042, 0.65867931],
       [0.25739544, 0.07131707, 0.89958839, 0.35358383],
       [0.26121198, 0.63580717, 0.17218271, 0.56051771],
       [0.18823925, 0.23221033, 0.15038527, 0.4345907 ],
       [0.98315254, 0.98988915, 0.90418925, 0.95659191],
       [0.34084185, 0.41572789, 0.53627904, 0.014084  ],
       [0.63100148, 0.39094767, 0.93505839, 0.46142078],
       [0.91659057, 0.25762495, 0.97818706, 0.58708503],
       [0.77195934, 0.78787311, 0.98150031, 0.90164449],
       [0.36801399, 0.92446502, 0.27334899, 0.70619269]])

In [10]:
np.reshape(a, a.size)

array([0.03038324, 0.83930041, 0.36571042, 0.65867931, 0.25739544,
       0.07131707, 0.89958839, 0.35358383, 0.26121198, 0.63580717,
       0.17218271, 0.56051771, 0.18823925, 0.23221033, 0.15038527,
       0.4345907 , 0.98315254, 0.98988915, 0.90418925, 0.95659191,
       0.34084185, 0.41572789, 0.53627904, 0.014084  , 0.63100148,
       0.39094767, 0.93505839, 0.46142078, 0.91659057, 0.25762495,
       0.97818706, 0.58708503, 0.77195934, 0.78787311, 0.98150031,
       0.90164449, 0.36801399, 0.92446502, 0.27334899, 0.70619269])

In [11]:
np.reshape(a,(a.size, 1, 1)).shape

(40, 1, 1)

In [12]:
print(a.shape)
print(a.size)

(10, 4)
40


In [13]:
# first row
a[0]

array([0.03038324, 0.83930041, 0.36571042, 0.65867931])

In [14]:
# first column
a[:,0]

array([0.03038324, 0.25739544, 0.26121198, 0.18823925, 0.98315254,
       0.34084185, 0.63100148, 0.91659057, 0.77195934, 0.36801399])

In [15]:
#como accedere a un elemento
#[x,y] la x es la fila y la y la columna
num = a[0,1]

0.8393004139688695

In [17]:
#luego se puede convertir en un entero

int(a[0,1] * 100)

83

In [27]:
#numero randomn entro dos numeros y un array predefinido
np.random.randint(low=0, high=100, size=(10,4))

array([[94, 79, 21, 59],
       [ 1, 90, 96, 73],
       [ 8, 73, 82, 13],
       [79, 44,  8, 83],
       [55, 99, 33, 47],
       [ 9, 54, 19, 68],
       [60, 73, 52, 64],
       [24, 22, 76, 12],
       [12, 89, 35, 68],
       [58, 27, 61, 15]])

In [30]:
np.reshape(a, a.size)

array([0.03038324, 0.83930041, 0.36571042, 0.65867931, 0.25739544,
       0.07131707, 0.89958839, 0.35358383, 0.26121198, 0.63580717,
       0.17218271, 0.56051771, 0.18823925, 0.23221033, 0.15038527,
       0.4345907 , 0.98315254, 0.98988915, 0.90418925, 0.95659191,
       0.34084185, 0.41572789, 0.53627904, 0.014084  , 0.63100148,
       0.39094767, 0.93505839, 0.46142078, 0.91659057, 0.25762495,
       0.97818706, 0.58708503, 0.77195934, 0.78787311, 0.98150031,
       0.90164449, 0.36801399, 0.92446502, 0.27334899, 0.70619269])

In [31]:
np.reshape(a, (a.size, 1, 1)).shape

(40, 1, 1)

In [32]:
print(a.shape)
print(a.size)

(10, 4)
40


In [33]:
#firstrow
a[:0,]

array([], shape=(0, 4), dtype=float64)

In [35]:
#firsticolum
a:[,:1]

SyntaxError: invalid syntax (<ipython-input-35-5600c4ff2427>, line 2)